server:
  port: 8081

---
spring:
  profiles:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/moneywaves?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update